=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::Attach
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::Attach do
  let(:instance) { WebullApiClient::Attach.new }

  describe 'test an instance of Attach' do
    it 'should create an instance of Attach' do
      expect(instance).to be_instance_of(WebullApiClient::Attach)
    end
  end
  describe 'test attribute "hkex_privilege"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
