=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::GetFundamentalsResponseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::GetFundamentalsResponseData do
  let(:instance) { WebullApiClient::GetFundamentalsResponseData.new }

  describe 'test an instance of GetFundamentalsResponseData' do
    it 'should create an instance of GetFundamentalsResponseData' do
      expect(instance).to be_instance_of(WebullApiClient::GetFundamentalsResponseData)
    end
  end
  describe 'test attribute "currency_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "points"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "title"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
