=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::GetStockAnalysisResponseForecastEpsPoints
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::GetStockAnalysisResponseForecastEpsPoints do
  let(:instance) { WebullApiClient::GetStockAnalysisResponseForecastEpsPoints.new }

  describe 'test an instance of GetStockAnalysisResponseForecastEpsPoints' do
    it 'should create an instance of GetStockAnalysisResponseForecastEpsPoints' do
      expect(instance).to be_instance_of(WebullApiClient::GetStockAnalysisResponseForecastEpsPoints)
    end
  end
  describe 'test attribute "value_actual"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "value_forecast"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "x_axis"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
