=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::GetAccountsResponseV5Positions2
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::GetAccountsResponseV5Positions2 do
  let(:instance) { WebullApiClient::GetAccountsResponseV5Positions2.new }

  describe 'test an instance of GetAccountsResponseV5Positions2' do
    it 'should create an instance of GetAccountsResponseV5Positions2' do
      expect(instance).to be_instance_of(WebullApiClient::GetAccountsResponseV5Positions2)
    end
  end
  describe 'test attribute "combo_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "combo_ticker_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "positions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
