=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::GetStockAnalysisResponseRating
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::GetStockAnalysisResponseRating do
  let(:instance) { WebullApiClient::GetStockAnalysisResponseRating.new }

  describe 'test an instance of GetStockAnalysisResponseRating' do
    it 'should create an instance of GetStockAnalysisResponseRating' do
      expect(instance).to be_instance_of(WebullApiClient::GetStockAnalysisResponseRating)
    end
  end
  describe 'test attribute "rating_analysis"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rating_analysis_totals"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "rating_spread"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
