=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::GetFundamentalsResponseAnalysis
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::GetFundamentalsResponseAnalysis do
  let(:instance) { WebullApiClient::GetFundamentalsResponseAnalysis.new }

  describe 'test an instance of GetFundamentalsResponseAnalysis' do
    it 'should create an instance of GetFundamentalsResponseAnalysis' do
      expect(instance).to be_instance_of(WebullApiClient::GetFundamentalsResponseAnalysis)
    end
  end
  describe 'test attribute "datas"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "industry_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "total_count"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
