=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for WebullApiClient::OrderType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe WebullApiClient::OrderType do
  let(:instance) { WebullApiClient::OrderType.new }

  describe 'test an instance of OrderType' do
    it 'should create an instance of OrderType' do
      expect(instance).to be_instance_of(WebullApiClient::OrderType)
    end
  end
end
