=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WebullApiClient::AlertsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AlertsApi' do
  before do
    # run before each test
    @api_instance = WebullApiClient::AlertsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertsApi' do
    it 'should create an instance of AlertsApi' do
      expect(@api_instance).to be_instance_of(WebullApiClient::AlertsApi)
    end
  end

  # unit tests for get_alerts
  # getAlerts
  # getAlerts
  # @param did Device ID
  # @param access_token Access token
  # @param [Hash] opts the optional parameters
  # @return [Array<GetAlertsResponse>]
  describe 'get_alerts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
