=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WebullApiClient::AuthenticationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationApi' do
  before do
    # run before each test
    @api_instance = WebullApiClient::AuthenticationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationApi' do
    it 'should create an instance of AuthenticationApi' do
      expect(@api_instance).to be_instance_of(WebullApiClient::AuthenticationApi)
    end
  end

  # unit tests for get_multi_factor_auth
  # getMultiFactorAuth
  # @param did Device ID
  # @param account account
  # @param account_type phone &#x3D; 1, email &#x3D; 2
  # @param device_id deviceId
  # @param code_type codeType
  # @param region_code regionCode
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_multi_factor_auth test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_trade_token
  # getTradeToken
  # Trading related authorize trade, must be done before trade action. Note: ensure &#39;pwd&#39; is your trade PIN. Your password isn&#39;t used here.&#39;
  # @param did Device ID
  # @param access_token Access token
  # @param [Hash] opts the optional parameters
  # @option opts [PostLoginParametersRequest] :post_login_parameters_request 
  # @return [Array<PostTradeTokenResponse>]
  describe 'get_trade_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for login
  # login
  # @param did Device ID
  # @param [Hash] opts the optional parameters
  # @option opts [PostLoginParametersRequest] :post_login_parameters_request 
  # @return [PostLoginResponse]
  describe 'login test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for logout
  # logout
  # Logout of your current session
  # @param did Device ID
  # @param access_token Access token
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'logout test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_token
  # refreshToken
  # Refresh user login token
  # @param did Device ID
  # @param access_token Access token
  # @param refresh_token Refresh token
  # @param [Hash] opts the optional parameters
  # @return [Array<PostRefreshTokenResponse>]
  describe 'refresh_token test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
