=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WebullApiClient::StocksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StocksApi' do
  before do
    # run before each test
    @api_instance = WebullApiClient::StocksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StocksApi' do
    it 'should create an instance of StocksApi' do
      expect(@api_instance).to be_instance_of(WebullApiClient::StocksApi)
    end
  end

  # unit tests for get_active_gainers_losers
  # getActiveGainersLosers
  # Active gainers / losers
  # @param did Device ID
  # @param access_token Access token
  # @param direction Direction
  # @param region_id regionId
  # @param user_region_id userRegionId
  # @param [Hash] opts the optional parameters
  # @return [Array<ActiveGainersLosers>]
  describe 'get_active_gainers_losers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_fundamentals
  # getFundamentals
  # getFundamentals
  # @param did Device ID
  # @param access_token Access token
  # @param stock Internal stock ticker ID
  # @param [Hash] opts the optional parameters
  # @return [Array<GetFundamentalsResponse>]
  describe 'get_fundamentals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_stock_analysis
  # getStockAnalysis
  # Analyze stock based on it&#39;s ticker
  # @param did Device ID
  # @param access_token Access token
  # @param stock Internal stock ticker ID
  # @param [Hash] opts the optional parameters
  # @return [GetStockAnalysisResponse]
  describe 'get_stock_analysis test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_stock_id
  # getStockID
  # Lookup stock ID
  # @param did Device ID
  # @param access_token Access token
  # @param keys Stock ticker
  # @param query_number queryNumber
  # @param [Hash] opts the optional parameters
  # @return [LookupTickerResponse]
  describe 'get_stock_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_stock_news
  # getStockNews
  # @param did Device ID
  # @param access_token Access token
  # @param stock Stocks internal ticker ID
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :current_news_id 0 is the latest article
  # @option opts [Integer] :page_size Number of articles
  # @return [GetNewsResponse]
  describe 'get_stock_news test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ticker_chart
  # getTickerChart
  # Stock symbol to get chart data
  # @param did Device ID
  # @param access_token Access token
  # @param stock Internal stock symbol ID
  # @param count Number of bars to return
  # @param extend_trading Whether to include pre-market and afterhours bars. &#39;1&#39; is used for pre-market and after-hours bars.
  # @param type X
  # @param [Hash] opts the optional parameters
  # @return [GetTickerChartResponse]
  describe 'get_ticker_chart test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for screener
  # screener
  # screener (TODO)
  # @param did Device ID
  # @param access_token Access token
  # @param fetch fetch
  # @param rules rules
  # @param sort sort
  # @param attach attach
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'screener test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
