=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'spec_helper'
require 'json'

# Unit tests for WebullApiClient::WebApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebApi' do
  before do
    # run before each test
    @api_instance = WebullApiClient::WebApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebApi' do
    it 'should create an instance of WebApi' do
      expect(@api_instance).to be_instance_of(WebullApiClient::WebApi)
    end
  end

  # unit tests for cancel_option_order
  # cancelOptionOrder
  # Cancel an option order
  # @param did Device ID
  # @param access_token Access token
  # @param t_token Trade token
  # @param t_time Time
  # @param sec_account_id Account ID
  # @param serial_id UUID
  # @param combo_id Order combo ID
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'cancel_option_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_orders
  # listOrders
  # List all orders matching optional filter values.
  # @param did Device ID
  # @param access_token Access token
  # @param t_time Time
  # @param t_token Trade token
  # @param sec_account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [PostOrderListRequest] :post_order_list_request 
  # @return [Array<Object>]
  describe 'list_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for place_option_order
  # placeOptionOrder
  # Place an option order
  # @param did Device ID
  # @param access_token Access token
  # @param t_token Trade token
  # @param t_time Time
  # @param sec_account_id secAccountId
  # @param [Hash] opts the optional parameters
  # @option opts [PostOptionOrderRequest] :post_option_order_request 
  # @return [Object]
  describe 'place_option_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for replace_option_order
  # replaceOptionOrder
  # @param did Device ID
  # @param access_token Access token
  # @param t_token Trade token
  # @param t_time Time
  # @param sec_account_id Account ID
  # @param [Hash] opts the optional parameters
  # @option opts [PostOptionOrderRequest] :post_option_order_request 
  # @return [Object]
  describe 'replace_option_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
