=begin
#Webull API

#Webull API Documentation

The version of the OpenAPI document: 3.0.1
Contact: austin.millan@gmail.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.1

=end

require 'date'
require 'time'

module WebullApiClient
  class GetAccountResponse
    attr_accessor :account_members

    attr_accessor :account_type

    attr_accessor :banners

    attr_accessor :broker_account_id

    attr_accessor :broker_id

    attr_accessor :currency

    attr_accessor :currency_id

    attr_accessor :deposits

    attr_accessor :net_liquidation

    attr_accessor :open_ipo_orders

    attr_accessor :open_order_size

    attr_accessor :open_orders

    attr_accessor :pdt

    attr_accessor :positions

    attr_accessor :professional

    attr_accessor :sec_account_id

    attr_accessor :show_upgrade

    attr_accessor :total_cost

    attr_accessor :unrealized_profit_loss

    attr_accessor :unrealized_profit_loss_base

    attr_accessor :unrealized_profit_loss_rate

    attr_accessor :warning

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_members' => :'accountMembers',
        :'account_type' => :'accountType',
        :'banners' => :'banners',
        :'broker_account_id' => :'brokerAccountId',
        :'broker_id' => :'brokerId',
        :'currency' => :'currency',
        :'currency_id' => :'currencyId',
        :'deposits' => :'deposits',
        :'net_liquidation' => :'netLiquidation',
        :'open_ipo_orders' => :'openIpoOrders',
        :'open_order_size' => :'openOrderSize',
        :'open_orders' => :'openOrders',
        :'pdt' => :'pdt',
        :'positions' => :'positions',
        :'professional' => :'professional',
        :'sec_account_id' => :'secAccountId',
        :'show_upgrade' => :'showUpgrade',
        :'total_cost' => :'totalCost',
        :'unrealized_profit_loss' => :'unrealizedProfitLoss',
        :'unrealized_profit_loss_base' => :'unrealizedProfitLossBase',
        :'unrealized_profit_loss_rate' => :'unrealizedProfitLossRate',
        :'warning' => :'warning'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_members' => :'Array<GetAcccountRequestAccountMembers>',
        :'account_type' => :'String',
        :'banners' => :'Array<GetAcccountRequestBanners>',
        :'broker_account_id' => :'String',
        :'broker_id' => :'Integer',
        :'currency' => :'String',
        :'currency_id' => :'Integer',
        :'deposits' => :'Array<Object>',
        :'net_liquidation' => :'String',
        :'open_ipo_orders' => :'Array<Object>',
        :'open_order_size' => :'Integer',
        :'open_orders' => :'Array<Object>',
        :'pdt' => :'Boolean',
        :'positions' => :'Array<GetAccountResponsePositions>',
        :'professional' => :'Boolean',
        :'sec_account_id' => :'Integer',
        :'show_upgrade' => :'Boolean',
        :'total_cost' => :'String',
        :'unrealized_profit_loss' => :'String',
        :'unrealized_profit_loss_base' => :'Float',
        :'unrealized_profit_loss_rate' => :'String',
        :'warning' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WebullApiClient::GetAccountResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WebullApiClient::GetAccountResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_members')
        if (value = attributes[:'account_members']).is_a?(Array)
          self.account_members = value
        end
      end

      if attributes.key?(:'account_type')
        self.account_type = attributes[:'account_type']
      end

      if attributes.key?(:'banners')
        if (value = attributes[:'banners']).is_a?(Array)
          self.banners = value
        end
      end

      if attributes.key?(:'broker_account_id')
        self.broker_account_id = attributes[:'broker_account_id']
      end

      if attributes.key?(:'broker_id')
        self.broker_id = attributes[:'broker_id']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'currency_id')
        self.currency_id = attributes[:'currency_id']
      end

      if attributes.key?(:'deposits')
        if (value = attributes[:'deposits']).is_a?(Array)
          self.deposits = value
        end
      end

      if attributes.key?(:'net_liquidation')
        self.net_liquidation = attributes[:'net_liquidation']
      end

      if attributes.key?(:'open_ipo_orders')
        if (value = attributes[:'open_ipo_orders']).is_a?(Array)
          self.open_ipo_orders = value
        end
      end

      if attributes.key?(:'open_order_size')
        self.open_order_size = attributes[:'open_order_size']
      end

      if attributes.key?(:'open_orders')
        if (value = attributes[:'open_orders']).is_a?(Array)
          self.open_orders = value
        end
      end

      if attributes.key?(:'pdt')
        self.pdt = attributes[:'pdt']
      end

      if attributes.key?(:'positions')
        if (value = attributes[:'positions']).is_a?(Array)
          self.positions = value
        end
      end

      if attributes.key?(:'professional')
        self.professional = attributes[:'professional']
      end

      if attributes.key?(:'sec_account_id')
        self.sec_account_id = attributes[:'sec_account_id']
      end

      if attributes.key?(:'show_upgrade')
        self.show_upgrade = attributes[:'show_upgrade']
      end

      if attributes.key?(:'total_cost')
        self.total_cost = attributes[:'total_cost']
      end

      if attributes.key?(:'unrealized_profit_loss')
        self.unrealized_profit_loss = attributes[:'unrealized_profit_loss']
      end

      if attributes.key?(:'unrealized_profit_loss_base')
        self.unrealized_profit_loss_base = attributes[:'unrealized_profit_loss_base']
      end

      if attributes.key?(:'unrealized_profit_loss_rate')
        self.unrealized_profit_loss_rate = attributes[:'unrealized_profit_loss_rate']
      end

      if attributes.key?(:'warning')
        self.warning = attributes[:'warning']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_members == o.account_members &&
          account_type == o.account_type &&
          banners == o.banners &&
          broker_account_id == o.broker_account_id &&
          broker_id == o.broker_id &&
          currency == o.currency &&
          currency_id == o.currency_id &&
          deposits == o.deposits &&
          net_liquidation == o.net_liquidation &&
          open_ipo_orders == o.open_ipo_orders &&
          open_order_size == o.open_order_size &&
          open_orders == o.open_orders &&
          pdt == o.pdt &&
          positions == o.positions &&
          professional == o.professional &&
          sec_account_id == o.sec_account_id &&
          show_upgrade == o.show_upgrade &&
          total_cost == o.total_cost &&
          unrealized_profit_loss == o.unrealized_profit_loss &&
          unrealized_profit_loss_base == o.unrealized_profit_loss_base &&
          unrealized_profit_loss_rate == o.unrealized_profit_loss_rate &&
          warning == o.warning
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_members, account_type, banners, broker_account_id, broker_id, currency, currency_id, deposits, net_liquidation, open_ipo_orders, open_order_size, open_orders, pdt, positions, professional, sec_account_id, show_upgrade, total_cost, unrealized_profit_loss, unrealized_profit_loss_base, unrealized_profit_loss_rate, warning].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = WebullApiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
